services:
  - type: web
    name: yfinance-proxy
    runtime: python
    repo: https://github.com/farrukhqayum/yfinance-proxy/
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
